github.com:
    users:
        Rossy0109:
            oauth_token: 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
    git_protocol: https
    user: Rossy0109
    oauth_token: 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
