-- 💰 Foot Print of Money - Supabase (PostgreSQL) Schema
-- Optimized with Security and Performance Best Practices

-- 1. Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Accounts Table
CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    account_name TEXT NOT NULL,
    account_type TEXT NOT NULL CHECK (account_type IN ('আয়', 'খরচ')),
    category TEXT,
    icon TEXT DEFAULT '💰',
    color TEXT DEFAULT '#1976D2',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, account_name)
);

-- 3. Payment Methods Table
CREATE TABLE payment_methods (
    method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    method_name TEXT NOT NULL,
    method_type TEXT CHECK (method_type IN ('নগদ', 'ব্যাংক', 'মোবাইল ব্যাংকিং', 'কার্ড')),
    balance DECIMAL(15,2) DEFAULT 0,
    icon TEXT DEFAULT '💵',
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE (user_id, method_name)
);

-- 4. Transactions Table
CREATE TABLE transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) DEFAULT auth.uid(),
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    transaction_time TIME DEFAULT CURRENT_TIME,
    account_id BIGINT REFERENCES accounts(account_id),
    amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    description TEXT,
    payment_method_id BIGINT REFERENCES payment_methods(method_id),
    receipt_url TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Performance Indexes
CREATE INDEX idx_transactions_account_id ON transactions(account_id);
CREATE INDEX idx_transactions_payment_method_id ON transactions(payment_method_id);
CREATE INDEX idx_transactions_date ON transactions(transaction_date DESC);
CREATE INDEX idx_accounts_user_id ON accounts(user_id);
CREATE INDEX idx_payment_methods_user_id ON payment_methods(user_id);
CREATE INDEX idx_transactions_user_id ON transactions(user_id);

-- 6. Enable Row-Level Security (RLS)
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- 7. Security Policies (Strict User Isolation with Performance Optimization)
CREATE POLICY "Users can manage their own accounts" 
    ON accounts FOR ALL 
    USING ((select auth.uid()) = user_id) 
    WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY "Users can manage their own payment methods" 
    ON payment_methods FOR ALL 
    USING ((select auth.uid()) = user_id) 
    WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY "Users can manage their own transactions" 
    ON transactions FOR ALL 
    USING ((select auth.uid()) = user_id) 
    WITH CHECK ((select auth.uid()) = user_id);

-- 8. Automatic Balance Management Trigger
CREATE OR REPLACE FUNCTION update_payment_method_balance()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE payment_methods 
        SET balance = balance + (
            CASE 
                WHEN (SELECT account_type FROM accounts WHERE account_id = NEW.account_id) = 'আয়' THEN NEW.amount 
                ELSE -NEW.amount 
            END
        )
        WHERE method_id = NEW.payment_method_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE payment_methods 
        SET balance = balance - (
            CASE 
                WHEN (SELECT account_type FROM accounts WHERE account_id = OLD.account_id) = 'আয়' THEN OLD.amount 
                ELSE -OLD.amount 
            END
        )
        WHERE method_id = OLD.payment_method_id;
    ELSIF (TG_OP = 'UPDATE') THEN
        -- Revert old amount
        UPDATE payment_methods 
        SET balance = balance - (
            CASE 
                WHEN (SELECT account_type FROM accounts WHERE account_id = OLD.account_id) = 'আয়' THEN OLD.amount 
                ELSE -OLD.amount 
            END
        )
        WHERE method_id = OLD.payment_method_id;
        
        -- Apply new amount
        UPDATE payment_methods 
        SET balance = balance + (
            CASE 
                WHEN (SELECT account_type FROM accounts WHERE account_id = NEW.account_id) = 'আয়' THEN NEW.amount 
                ELSE -NEW.amount 
            END
        )
        WHERE method_id = NEW.payment_method_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE EXECUTE ON FUNCTION update_payment_method_balance() FROM public, anon, authenticated;

CREATE TRIGGER trg_update_balance
AFTER INSERT OR UPDATE OR DELETE ON transactions
FOR EACH ROW EXECUTE FUNCTION update_payment_method_balance();
