[gdrive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AQvPyIPnPGzp5EMtIzAZ_h9nYaU1FXfAIJcGKLWsNoIfSWgPl05Q2Iq5DBMhp7_MvpqpQscq94ecJlM8mPwxuXtyREKPqDhTYHEkYEesDxUm8lqyPNpnqECBJjpYq8Sjjt_pIHllh3p2ZDTWpGqghd1eo0g0VXP3ZrCjYy1s3ET5Y2zM2Io-mZ9ro1ZVSmqpKjKcpPwtaCgYKAS8SAQ8SFQHGX2MiZJrGp5OhEH0QpQnE2ObxeQ0207","token_type":"Bearer","refresh_token":"1//0gocUUaBgMAYbCgYIARAAGBASNwF-L9Irn1IutDM4oTi7sJ94TtX9ywUcicN7JQl4ouFUQAZK5I6_oe5w_1MUkuWucnn1VE7nQDc","expiry":"2026-05-18T21:49:36.934024753Z","expires_in":3599}
metadata_labels = read,write
auth_url = .

