name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: cd Foot_Print_of_Money && npm install

      - name: Run Tests
        run: cd Foot_Print_of_Money && npx playwright install --with-deps && npm test
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          channelId: live
          projectId: ahmeed-steel-industry
          entryPoint: Foot_Print_of_Money

  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0
      - name: Deploy to Vercel
        run: cd Foot_Print_of_Money/frontend && npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
