name: Release Note

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get release notes
        run: |
          echo "Release triggered for tag $GITHUB_REF" 
          git --no-pager log -n 10 --pretty=format:'%h %s' ${GITHUB_REF}
